#!/usr/bin/env python3
"""
Generate infusion gacha box spec — 12 boxes (4 slots x 3 grades).

Each box awards one random infusion gear piece of the matching slot and grade.
Item IDs are computed from the known interleaving pattern in 06-gear-infusion-items.yaml.

Usage:
    python tools/gear-infusion/generate_infusion_boxes.py [--patch 001]

Output:
    specs/patches/{patch}/15-infusion-boxes.yaml
"""

import argparse
import os
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

BOX_ID_START = 602190

GRADES = ["Uncommon", "Rare", "Superior"]

SLOT_CONFIGS = [
    {
        "slot": "Weapon",
        "start": 860000,
        "passivities": 15,
        "subtypes": 13,
        "block_size": 39,
        "grade_offsets": {
            "Uncommon": (0, 13),
            "Rare": (13, 26),
            "Superior": (26, 39),
        },
    },
    {
        "slot": "Chest",
        "start": 860585,
        "passivities": 18,
        "subtypes": 3,
        "block_size": 9,
        "grade_offsets": {
            "Uncommon": (0, 3),
            "Rare": (3, 6),
            "Superior": (6, 9),
        },
    },
    {
        "slot": "Gloves",
        "start": 860747,
        "passivities": 10,
        "subtypes": 3,
        "block_size": 9,
        "grade_offsets": {
            "Uncommon": (0, 3),
            "Rare": (3, 6),
            "Superior": (6, 9),
        },
    },
    {
        "slot": "Boots",
        "start": 860837,
        "passivities": 7,
        "subtypes": 3,
        "block_size": 9,
        "grade_offsets": {
            "Uncommon": (0, 3),
            "Rare": (3, 6),
            "Superior": (6, 9),
        },
    },
]

# Box rareGrade matches the infusion grade inside
GRADE_RARE_VALUES = {"Uncommon": 1, "Rare": 2, "Superior": 3}

# Expected pool sizes for validation
EXPECTED_POOL_SIZES = {
    "Weapon": 195,
    "Chest": 54,
    "Gloves": 30,
    "Boots": 21,
}


# ---------------------------------------------------------------------------
# Pool computation
# ---------------------------------------------------------------------------

def build_reward_pools() -> dict[tuple[str, str], list[int]]:
    """Compute per-slot per-grade item ID lists from the interleaving pattern.

    Returns dict keyed by (slot_name, grade_name) -> sorted list of item IDs.
    """
    pools: dict[tuple[str, str], list[int]] = {}
    for sc in SLOT_CONFIGS:
        for grade in GRADES:
            ids = []
            lo, hi = sc["grade_offsets"][grade]
            for p in range(sc["passivities"]):
                block_base = sc["start"] + p * sc["block_size"]
                ids.extend(range(block_base + lo, block_base + hi))
            pools[(sc["slot"], grade)] = ids
    return pools


def validate_pools(pools: dict[tuple[str, str], list[int]]) -> None:
    """Verify pool sizes match expected counts."""
    for sc in SLOT_CONFIGS:
        for grade in GRADES:
            key = (sc["slot"], grade)
            actual = len(pools[key])
            expected = EXPECTED_POOL_SIZES[sc["slot"]]
            assert actual == expected, (
                f"Pool {key}: expected {expected} items, got {actual}"
            )


# ---------------------------------------------------------------------------
# YAML generation
# ---------------------------------------------------------------------------

def generate_yaml(pools: dict[tuple[str, str], list[int]]) -> str:
    """Generate the full gachaItems spec YAML."""
    lines = [
        "# Infusion Gacha Boxes — Patch 001",
        "# 12 boxes: 4 equipment slots x 3 grades.",
        "# Each box awards one random infusion gear piece of the matching slot/grade.",
        "# Auto-generated by tools/gear-infusion/generate_infusion_boxes.py",
        "# DO NOT EDIT MANUALLY",
        "",
        "spec:",
        '  version: "1.0"',
        "  schema: v92",
        "",
        "imports:",
        "  - from: gear-infusion-boxes",
        "    use:",
        "      variables:",
    ]

    # Import all box ID variables
    for sc in SLOT_CONFIGS:
        for grade in GRADES:
            var = f"INFUSION_{sc['slot'].upper()}_BOX_{grade.upper()}"
            lines.append(f"        - {var}")

    lines.append("")
    lines.append("definitions:")
    lines.append("  infusionBoxBase:")
    lines.append("    maxStack: 100")
    lines.append("    tradable: true")
    lines.append("    warehouseStorable: true")
    lines.append("    boundType: None")
    lines.append("")
    lines.append("gachaItems:")
    lines.append("  upsert:")

    for sc in SLOT_CONFIGS:
        for grade in GRADES:
            var = f"INFUSION_{sc['slot'].upper()}_BOX_{grade.upper()}"
            item_ids = pools[(sc["slot"], grade)]
            pool_size = len(item_ids)
            title = f"Infusion {sc['slot']} Box ({grade})"
            memo = f"Contains a random {grade.lower()} infusion {sc['slot'].lower()}."
            rare_grade = GRADE_RARE_VALUES[grade]

            lines.append(f"    # {title} — {pool_size} items")
            lines.append(f"    - itemTemplateId: ${var}")
            lines.append(f'      title: "{title}"')
            lines.append(f'      sender: "Infusion System"')
            lines.append(f'      memo: "{memo}"')
            lines.append("      item:")
            lines.append("        $extends: infusionBoxBase")
            lines.append("        icon: Icon_Items.Cash_Material_box_3_Tex")
            lines.append(f"        rareGrade: {rare_grade}")
            lines.append("      randomRewards:")
            lines.append("        - equalProbability: 6")
            lines.append("          rewards:")
            for iid in item_ids:
                lines.append(f"            - itemTemplateId: {iid}")
            lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate infusion gacha box spec"
    )
    parser.add_argument(
        "--patch", default="001", help="Patch number (default: 001)"
    )
    args = parser.parse_args()

    # Resolve paths relative to reforged/ root
    script_dir = Path(__file__).resolve().parent
    reforged_root = script_dir.parent.parent
    specs_dir = reforged_root / "specs" / "patches" / args.patch
    output_path = specs_dir / "15-infusion-boxes.yaml"

    # Build and validate pools
    pools = build_reward_pools()
    validate_pools(pools)

    # Generate YAML
    yaml_content = generate_yaml(pools)

    # Write output
    os.makedirs(specs_dir, exist_ok=True)
    with open(str(output_path), "w", encoding="utf-8", newline="\n") as f:
        f.write(yaml_content)

    # Summary
    total_items = sum(len(v) for v in pools.values())
    print(f"Generated {output_path.relative_to(reforged_root)}")
    print(f"  Boxes: 12 (4 slots x 3 grades)")
    print(f"  Total reward items: {total_items}")
    for sc in SLOT_CONFIGS:
        size = EXPECTED_POOL_SIZES[sc["slot"]]
        print(f"  {sc['slot']}: {size} items per grade")


if __name__ == "__main__":
    main()
