#!/usr/bin/env python
"""Generate the IoD patch 001 quest re-enable + Stepstone disable specs (Stage 4B).

Two outputs:
  specs/patches/001/09-iod-quest-enable.yaml   (63 v17 island quests)
  specs/patches/001/10-iod-stepstone-disable.yaml (Stepstone chain head 59901)

TARGET AUTHORITY (decision 6): v17.11 is the north star; v31 is a baseline proxy
only. This generator does NOT trust the proxy for current state. For every one of
the 63 roster quests it reads the ACTUAL live v92 QuestData header and emits an op
ONLY where the live value differs from the v17 target. That makes the spec minimal
(no zero-command operations -> no W503 warnings) and idempotent by construction.

Sources:
  - v17-quests.json  : v17 catalog (min/max level, story group, quest_type_raw,
                       accept mechanism, giver, prerequisite gids). North star.
  - live v92 headers : D:/dev/mmogate/tera92/server/Datasheet/QuestData/*.quest
                       (read-only) -> current state for the diff.
  - v31-quests.json  : drift-flag COUNTS only, used as a cross-check assertion.

Per-category op logic (each emits only on live!=target):
  prerequisites  requirements.prerequisites = [v17 gids]  (empty [] removes the
                 block entirely -> clears the 99,99 sentinel on the 40 disabled
                 quests and relinks the drifted chains). DSL takes GLOBAL quest ids
                 and resolves each to its Quest번호 ref (id -> id//100,id%100).
  minLevel       requirements.minLevel = v17 min_level (13 MINLEVEL_DRIFT).
  questType      header.questType = enum(v17 quest_type_raw)  (17 TYPE_DRIFT;
                 미션->Mission, 일반->General).
  giverNpc       header.giverNpc = v17 giver "zone,template"  (npc-accept quests
                 whose v17 giver drifted; 10 quests -- see accept note for the 11th).
  storyGroupId   header.storyGroupId = v17 story group id, SET only (6 quests).
                 The 12 DE-GROUPED quests need the header cleared to the canonical
                 empty <스토리그룹Id /> form -- NOT SUPPORTED by the current DSL
                 surface (storyGroupId is int?; null/"" -> no-op, 0 -> literal "0",
                 neither yields the empty element). These 12 header back-references
                 are DEFERRED here; their de-grouping is still enforced by
                 07-iod-story-groups.yaml (QuestGroupList membership is authoritative).

Settled decisions (override v17 where noted):
  Decision 3 / 1305: v17 auto-accept. Live v92 is npc-accept -> header.autoAccept
                 = true (this IS the single ACCEPT_DRIFT). It is an AUTOGRANT_CHAIN
                 trap point (auto-grant only fires if predecessor 1304 is active).
                 1305 keeps its residual NPC대화; v17 giver is null and clearing a
                 trigger to empty is unsupported (same gap as storyGroupId). Inert
                 for an auto quest; documented, not a fix here.
  Decision 10 / 1311: v17 has 1311 as auto-accept (AUTOGRANT_CHAIN); the settled
                 decision makes it NPC-accept instead, to remove the fresh-char trap.
                 -> header.autoAccept = false (removes 즉시수주) + header.giverNpc =
                 the natural giver = the NPC where quest 1310 turns in in v17, i.e.
                 v17 quest 1310's receiver = 64,1009 (already the live value; set
                 explicitly to document the decision).
  Decision 11 / 1379,1383: v92-keeps, absent from the v17 roster; the generator
                 never iterates them, so they receive NO ops (asserted).

DEFERRED (not authored here):
  - Receiver / turn-in drift (RECEIVER_DRIFT, 20 quests) lives in Task bodies, which
    remain blocked by the pending task-authoring surface. Listed in the 09 header.
  - The 12 story-group header back-reference clears (DSL clear-to-empty gap).
  - linkedQuest (연결퀘스트): the v17 old-client files carry NO 연결퀘스트 element
    for ANY of the 63 island quests (all absent); there is no LINKED_DRIFT signal,
    and clearing a live value to empty is unsupported. 0 ops.

10-iod-stepstone-disable.yaml: quest 59901 (Quest번호 599,1, Stepstone chain head,
  v92-only content, decision 2026-07-18). Set requirements.prerequisites = [9999];
  9999 resolves to the ref 99,99 (arithmetic id//100,id%100), the never-satisfiable
  sentinel that soft-disables the quest. Disabling the chain head blocks the chain.

Generated by tools/dc-restore/gen_enable_specs.py. Byte-deterministic (sorted ids).
"""

import json
import re
import sys
from pathlib import Path

REPO = Path("D:/dev/mmogate/github/reforged-server-content/reforged")
DATA = REPO / "docs/plans/iod-alpha-content-loop/data"
QD = Path("D:/dev/mmogate/tera92/server/Datasheet/QuestData")
OUT_ENABLE = REPO / "specs/patches/001/09-iod-quest-enable.yaml"
OUT_DISABLE = REPO / "specs/patches/001/10-iod-stepstone-disable.yaml"

KEEP_IDS = {1379, 1383}          # decision 11 -- never touched
STEPSTONE_ID = 59901             # decision 2026-07-18
SENTINEL_INT = 9999              # resolves to ref 99,99

TYPE_KR2EN = {
    "일반": "General", "일일": "Daily", "미션": "Mission",
    "중요미션": "ImportantMission", "길드": "Guild", "연맹": "Alliance",
    "추천일반": "RecommendedNormal", "검은틈": "DarkRift",
    "범용": "GeneralPurpose", "반복": "Repeatable",
}

# Expected drift counts (v31-quests.json flag_counts) -- cross-check assertions.
EXPECT = {
    "minlevel": 13, "type": 17, "accept_drift": 1,
    "storygroup": 18, "storyclear": 12, "storyset": 6,
    "sentinel": 40, "prereq_drift": 18, "giver_drift": 10,
}


def gid_to_ref(gid):
    return (gid // 100, gid % 100)


def ref_tuple(s):
    s = s.strip()
    if not s:
        return None
    a, b = s.split(",")
    return (int(a), int(b))


def read_header(qid):
    """Extract the BASELINE v92 header state needed for the diff.

    Reads from the datasheet repo's git HEAD, not the working tree, so the
    generator is re-runnable after the patch has been applied (same principle
    as migrate's --source-ref). Falls back to the working tree only if the git
    read fails.
    """
    import subprocess
    repo = str(QD.parent.parent)
    rel = f"Datasheet/QuestData/{qid:06d}.quest"
    r = subprocess.run(["git", "-C", repo, "show", f"HEAD:{rel}"], capture_output=True)
    text = (r.stdout.decode("utf-8-sig", errors="replace") if r.returncode == 0
            else (QD / f"{qid:06d}.quest").read_text(encoding="utf-8"))
    h = text.split("</Header>")[0]

    def one(tag):
        if re.search(rf"<{tag}\s*/>", h):
            return None
        m = re.search(rf"<{tag}>([^<]*)</{tag}>", h, re.S)
        return m.group(1).strip() if m else None

    cond = re.search(r"<수행조건>.*?</수행조건>", h, re.S)
    condtxt = cond.group(0) if cond else ""
    occ = re.search(r"<발생조건>.*?</발생조건>", h, re.S)
    occtxt = occ.group(0) if occ else ""
    npc = re.search(r"<NPC대화>([^<]*)</NPC대화>", occtxt)
    prereqs = [ref_tuple(x) for x in re.findall(r"<퀘스트Id>([^<]*)</퀘스트Id>", condtxt)]
    return {
        "min": one("최소레벨"),
        "max": one("최대레벨"),
        "sg": one("스토리그룹Id"),
        "type": one("퀘스트종류"),
        "prereqs": [p for p in prereqs if p],
        "giver": npc.group(1).strip() if npc else None,
        "immediate": "<즉시수주>" in occtxt,
    }


def yaml_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    v17 = json.load(open(DATA / "v17-quests.json", encoding="utf-8"))
    v17q = {q["id"]: q for q in v17["quests"]}
    v31 = json.load(open(DATA / "v31-quests.json", encoding="utf-8"))
    flag_counts = v31["summary"]["flag_counts"]

    assert not (KEEP_IDS & set(v17q)), "keeps 1379/1383 must not be in the v17 roster"
    assert v17q[1310]["receiver"] == "64,1009", "1311 giver derives from 1310 receiver"

    # per-quest merged changes: {qid: {"header": {...}, "requirements": {...}}}
    changes = {}
    stats = {k: [] for k in
             ("prereq_set", "prereq_clear", "minlevel", "maxlevel", "giver",
              "storyset", "storyclear", "type", "accept_drift")}

    def hdr(qid):
        return changes.setdefault(qid, {}).setdefault("header", {})

    def req(qid):
        return changes.setdefault(qid, {}).setdefault("requirements", {})

    for qid in sorted(v17q):
        q = v17q[qid]
        cur = read_header(qid)

        # --- prerequisites ---
        tgt_gids = [p["gid"] for p in q["prereqs"]]
        # Decision override 2026-07-19 (live-test finding): v92's 1303 carried an
        # OR list of the 9 class-training quests plus a 선행퀘스트논리식 element.
        # Clearing prereqs to the v17 empty state ORPHANS the logic operator
        # (DSL clear removes the block, not the sibling; corpus-unique shape)
        # and the quest becomes unofferable. Until the DSL can drop the logic
        # element, gate 1303 on 1304: matches the journal story order, always
        # satisfied at that point of the spine, and keeps the XML shape valid.
        if qid == 1303 and not tgt_gids:
            tgt_gids = [1304]
        tgt_refs = [gid_to_ref(g) for g in tgt_gids]
        if cur["prereqs"] != tgt_refs:
            req(qid)["prerequisites"] = tgt_gids  # [] clears the block
            (stats["prereq_set"] if tgt_gids else stats["prereq_clear"]).append(qid)

        # --- minLevel ---
        tmin = q.get("min_level")
        tmin = int(tmin) if tmin not in (None, "") else None
        cmin = int(cur["min"]) if cur["min"] else None
        if tmin is not None and tmin != cmin:
            req(qid)["minLevel"] = tmin
            stats["minlevel"].append(qid)

        # --- maxLevel (SET only; v17 island quests carry none, so expected empty) ---
        tmax = q.get("max_level")
        tmax = int(tmax) if tmax not in (None, "") else None
        cmax = int(cur["max"]) if cur["max"] else None
        if tmax is not None and tmax != cmax:
            req(qid)["maxLevel"] = tmax
            stats["maxlevel"].append(qid)

        # --- questType ---
        traw = q.get("quest_type_raw")
        if traw and cur["type"] != traw:
            en = TYPE_KR2EN.get(traw)
            assert en, f"unmapped quest_type_raw {traw!r} on quest {qid}"
            hdr(qid)["questType"] = en
            stats["type"].append(qid)

        # --- giverNpc (npc-accept, v17 giver present) ---
        tgiver = q.get("giver")
        if q.get("accept") == "npc" and tgiver and cur["giver"] != tgiver:
            hdr(qid)["giverNpc"] = tgiver
            stats["giver"].append(qid)

        # --- accept mechanism (drift toward v17) ---
        tgt_imm = (q.get("accept") == "auto")
        if tgt_imm != cur["immediate"]:
            hdr(qid)["autoAccept"] = tgt_imm
            stats["accept_drift"].append(qid)

        # --- storyGroupId ---
        tsg = q.get("story_group")
        tsg = int(tsg) if tsg not in (None, "") else None
        csg = int(cur["sg"]) if cur["sg"] else None
        if tsg is not None and csg != tsg:
            hdr(qid)["storyGroupId"] = tsg
            stats["storyset"].append(qid)
        elif tsg is None and csg is not None:
            stats["storyclear"].append(qid)  # DEFERRED (DSL clear-to-empty gap)

    # --- settled-decision override: 1311 NPC-accept + explicit giver ---
    hdr(1311)["autoAccept"] = False
    hdr(1311)["giverNpc"] = v17q[1310]["receiver"]  # 64,1009

    # ----- cross-check assertions against documented drift flags -----
    def check(name, got, want):
        if got != want:
            sys.exit(f"HARD FAIL: {name} count {got} != expected {want}")

    check("minlevel", len(stats["minlevel"]), EXPECT["minlevel"])
    check("type", len(stats["type"]), EXPECT["type"])
    check("accept_drift", len(stats["accept_drift"]), EXPECT["accept_drift"])
    check("storyset", len(stats["storyset"]), EXPECT["storyset"])
    check("storyclear", len(stats["storyclear"]), EXPECT["storyclear"])
    check("storygroup_total",
          len(stats["storyset"]) + len(stats["storyclear"]), EXPECT["storygroup"])
    check("giver_drift", len(stats["giver"]), EXPECT["giver_drift"])
    check("prereq_drift_nonsentinel",
          len([q for q in stats["prereq_set"] + stats["prereq_clear"]
               if (99, 99) not in read_header(q)["prereqs"]]),
          EXPECT["prereq_drift"])
    check("sentinel",
          len([q for q in stats["prereq_set"] + stats["prereq_clear"]
               if (99, 99) in read_header(q)["prereqs"]]),
          EXPECT["sentinel"])
    assert stats["accept_drift"] == [1305], "1305 is the only ACCEPT_DRIFT"
    assert not any(k in changes for k in KEEP_IDS), "keeps must be untouched"

    # ---------------- emit 09-iod-quest-enable.yaml ----------------
    receiver_drift = sorted(
        q["gid"] for q in v31["quests"] if "RECEIVER_DRIFT" in q["flags"])
    L = [
        "spec:",
        '  version: "1.0"',
        "  schema: v92",
        "",
        "# IoD patch 001 quest re-enable + v17 header/requirement alignment (Stage 4B).",
        "# Target authority: v17.11 north star (decision 6). Each op is emitted ONLY where",
        "#   the live v92 header differs from v17, so the spec is minimal and idempotent.",
        "# Prerequisites take GLOBAL quest ids (DSL resolves id -> Quest번호 id//100,id%100);",
        "#   an empty list removes the 선행퀘스트 block, clearing the 99,99 disable sentinel.",
        "#",
        "# Settled decisions:",
        "#   3  1305 -> auto-accept (autoAccept:true); the single ACCEPT_DRIFT. AUTOGRANT_CHAIN",
        "#      trap point (fires only if predecessor 1304 is active). Residual NPC대화 kept.",
        "#   10 1311 -> NPC-accept override of v17 auto (autoAccept:false) + giver 64,1009,",
        "#      the v17 turn-in NPC of quest 1310 (its receiver). Removes the fresh-char trap.",
        "#   11 1379,1383 -> v92-keeps, absent from roster, untouched.",
        "#",
        "# DEFERRED (not in this spec):",
        "#   - Receiver/turn-in drift (task bodies, blocked by task-authoring surface): "
        + ",".join(str(x) for x in receiver_drift),
        "#   - 12 story-group header back-reference CLEARS (DSL has no clear-to-empty for",
        "#     storyGroupId): " + ",".join(str(x) for x in sorted(stats["storyclear"])),
        "#     De-grouping is enforced by 07-iod-story-groups.yaml (QuestGroupList membership).",
        "#   - linkedQuest: v17 old-client has no 연결퀘스트 for any of the 63; 0 ops.",
        "#",
        "# Generated by tools/dc-restore/gen_enable_specs.py",
        "",
        "quests:",
        "  update:",
    ]

    HDR_ORDER = ["storyGroupId", "questType", "autoAccept", "giverNpc"]
    REQ_ORDER = ["minLevel", "maxLevel", "prerequisites"]

    def fmt(v):
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, list):
            return "[" + ", ".join(str(x) for x in v) + "]"
        if isinstance(v, str):
            return yaml_str(v)
        return str(v)

    for qid in sorted(changes):
        c = changes[qid]
        L.append(f"    - id: {qid}")
        L.append("      changes:")
        if c.get("header"):
            L.append("        header:")
            for k in HDR_ORDER:
                if k in c["header"]:
                    L.append(f"          {k}: {fmt(c['header'][k])}")
        if c.get("requirements"):
            L.append("        requirements:")
            for k in REQ_ORDER:
                if k in c["requirements"]:
                    L.append(f"          {k}: {fmt(c['requirements'][k])}")

    OUT_ENABLE.write_text("\n".join(L) + "\n", encoding="utf-8")

    # ---------------- emit 10-iod-stepstone-disable.yaml ----------------
    D = [
        "spec:",
        '  version: "1.0"',
        "  schema: v92",
        "",
        "# IoD patch 001 Stepstone disable (decision 2026-07-18).",
        "# Quest 59901 (Quest번호 599,1) is the Stepstone chain head. Stepstone is v92-only",
        "#   content, out of the classic-restoration scope; disabling the chain head blocks",
        "#   the whole chain. requirements.prerequisites = [9999] resolves to the ref 99,99",
        "#   (arithmetic id//100,id%100), the never-satisfiable sentinel used across IoD to",
        "#   soft-disable a quest (the quest can never be offered).",
        "#",
        "# Generated by tools/dc-restore/gen_enable_specs.py",
        "",
        "quests:",
        "  update:",
        f"    - id: {STEPSTONE_ID}",
        "      changes:",
        "        requirements:",
        f"          prerequisites: [{SENTINEL_INT}]",
    ]
    OUT_DISABLE.write_text("\n".join(D) + "\n", encoding="utf-8")

    # ---------------- report (stderr) ----------------
    print(f"Wrote {OUT_ENABLE}", file=sys.stderr)
    print(f"Wrote {OUT_DISABLE}", file=sys.stderr)
    print(f"quests changed in 09: {len(changes)}", file=sys.stderr)
    for k in ("prereq_set", "prereq_clear", "minlevel", "maxlevel", "giver",
              "storyset", "storyclear", "type", "accept_drift"):
        print(f"  {k}: {len(stats[k])} {sorted(stats[k])}", file=sys.stderr)
    print(f"  1311 giver = {v17q[1310]['receiver']} (v17 receiver of 1310)",
          file=sys.stderr)
    print(f"flag_counts (reference): {flag_counts}", file=sys.stderr)


if __name__ == "__main__":
    main()
