#!/usr/bin/env python
"""Generate the IoD patch 001 ECompensation restoration spec (v31-primary doctrine).

Source of truth is the v31 server ECompensation_13.xml, ported 1:1: every natural
mob-drop Compensation (GoldBag + ItemBag) is emitted verbatim, including the
`wValue` weight and `t` cache strings that the engine derives per bag.

Why this spec exists (root cause):
  In v92 the entire v31 natural-mob ECompensation_13 table is commented out; only
  the fierce-variant stubs 7001-7009 and the Sinus Thief 9001 remained active. The
  IoD mob "drops" visible in-game are CCompensation entries, but nearly all of them
  are ROOT ItemBags (no ClassItemBag wrapper). Per the loot-system rule "omitting
  class branching gives loot to no one", those root bags drop to nobody, which is
  exactly what patch-001 live tests showed (only the class-gated Mote bag worked).
  ECompensation is the confirmed-working server drop path. Patch-001 spec 20
  originally restored ONLY 300945 (First Expedition). This regenerates spec 20 to
  restore the FULL v31 ECompensation_13 table so every regular IoD mob drops its
  v31 gold + materials again.

Scope: hunting zone 13 only. v31 has no ECompensation for the other IoD zones
  (64/213/313/364 are villagers; 436/9036 have no E-table). 300945 stays included
  (First Expedition set), so its provenance in the divergence log is preserved.

Fidelity: bag ids, bagNames, probabilities, wValues, min/max, and `t` cache strings
  are copied verbatim from v31. Item `name` labels keep the v31 Korean internal
  names (inert; templateId is the key). Empty v31 Compensation stubs (no bags:
  102, 301, 1011, 999, 888, 111) are omitted (they drop nothing; upserting an empty
  entry is a no-op). `backLock=""` empty attributes are dropped (no data). No
  divergence from v31.

ECompensation is server-only (no client sync). Output is an idempotent upsert.
"""

import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path("D:/dev/mmogate/github/reforged-server-content/reforged")
V31_SRC = Path(
    "Z:/tera pserver/v31.04/TERAServer/Executable/Bin/Datasheet/CompensationData/ECompensation_13.xml"
)
OUT = REPO / "specs/patches/001/20-iod-ecomp-drops.yaml"

HUNTING_ZONE = 13


def q(s: str) -> str:
    """Double-quote a YAML string, escaping backslashes and quotes."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    root = ET.parse(str(V31_SRC)).getroot()

    lines: list[str] = []
    a = lines.append

    a("# IoD ECompensation Drops - Patch 001 (v31-primary restoration)")
    a("# Restores the FULL v31 open-world mob-drop table for Island of Dawn hunting")
    a("# zone 13, ported 1:1 from v31 ECompensation_13.xml.")
    a("#")
    a("# Generated by tools/dc-restore/gen_ecomp_restore.py (do not hand-edit).")
    a("#")
    a("# Root cause: v92 commented out the entire v31 natural-mob table; the visible")
    a("# CCompensation drops are root ItemBags with no ClassItemBag wrapper, which the")
    a("# engine gives to no one (confirmed in patch-001 live tests: nothing dropped).")
    a("# ECompensation is the confirmed-working server drop path. This spec restores")
    a("# gold + materials + designs + the First Expedition set (300945) for every v31")
    a("# IoD mob. Empty v31 stubs (102/301/1011/999/888/111) are omitted (no drops).")
    a("#")
    a("# Fidelity: bag ids, bagNames, probabilities, wValues, min/max, and `t` cache")
    a("# strings are verbatim from v31. Item names keep v31 Korean internal labels")
    a("# (inert; templateId is the key). Server-only (no client sync). No divergence.")
    a("")
    a("spec:")
    a('  version: "1.0"')
    a("  schema: v92")
    a("")
    a("eCompensations:")
    a("  upsert:")

    emitted = 0
    for comp in root.findall("Compensation"):
        gold_bags = comp.findall("GoldBag")
        item_bags = comp.findall("ItemBag")
        if not gold_bags and not item_bags:
            continue  # empty stub, drops nothing

        npc_id = comp.get("npcTemplateId")
        npc_name = comp.get("npcName", "")
        a(f"    - huntingZoneId: {HUNTING_ZONE}")
        a(f"      npcTemplateId: {npc_id}")
        a(f"      npcName: {q(npc_name)}")

        if gold_bags:
            a("      goldBags:")
            for gb in gold_bags:
                a(f"        - bagName: {q(gb.get('bagName', ''))}")
                a(f"          probability: {gb.get('probability')}")
                if gb.get("wValue") is not None:
                    a(f"          wValue: {gb.get('wValue')}")
                a(f"          min: {gb.get('min')}")
                a(f"          max: {gb.get('max')}")
                if gb.get("t"):
                    a(f"          t: {q(gb.get('t'))}")

        if item_bags:
            a("      itemBags:")
            for ib in item_bags:
                a(f"        - id: {ib.get('id')}")
                a(f"          bagName: {q(ib.get('bagName', ''))}")
                a(f"          probability: {ib.get('probability')}")
                if ib.get("wValue") is not None:
                    a(f"          wValue: {q(ib.get('wValue'))}")
                if ib.get("t"):
                    a(f"          t: {q(ib.get('t'))}")
                a("          items:")
                for it in ib.findall("Item"):
                    a(f"            - templateId: {it.get('templateId')}")
                    a(f"              name: {q(it.get('name', ''))}")
                    a(f"              min: {it.get('min', '1')}")
                    a(f"              max: {it.get('max', '1')}")
                    a(f"              probability: {it.get('probability')}")
        emitted += 1

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"Compensation entries emitted: {emitted}")


if __name__ == "__main__":
    main()
